name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }] # Atualiza diariamente
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}           # PAT para leitura
          committer_token: ${{ secrets.METRICS_TOKEN }} # PAT também para commit
          committer_branch: main
          committer_message: "chore: update metrics"
          filename: github-metrics.svg
          user: marceloteclas
          config_timezone: America/Bahia
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
